import { HeaderAdmin } from "@/components/reusable/header-admin";

import { SidebarAdmin } from "@/components/reusable/sidebar-admin";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Halaman Admin",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <SidebarAdmin />
      <main className="w-full">
        <HeaderAdmin />
        <div className="p-4">{children}</div>
      </main>
    </SidebarProvider>
  );
}
